# numpy

In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [6]:
np.__version__

'1.24.1'

In [36]:
z=np.zeros((5,5))
print((z))
    

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [37]:
z=np.zeros((10,10))
print("%d bytes" % (z.size * z.itemsize))
print(z)
print(z.size)
print(z.itemsize)

800 bytes
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
100
8


In [42]:
z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [59]:
s=np.arange(4,12)
print(type(s))
print(set(s))
print(s)


<class 'numpy.ndarray'>
{4, 5, 6, 7, 8, 9, 10, 11}
[ 4  5  6  7  8  9 10 11]


In [69]:
s=np.arange(12,30,3)
print(s.shape)
print(s.max())
print(s)

(6,)
27
[12 15 18 21 24 27]


In [74]:
d=s.reshape(3,2)
print(d)

[[12 15]
 [18 21]
 [24 27]]


In [7]:
z=np.arange(50)
z=(z[::-1]).reshape(10,5)
print(z)

[[49 48 47 46 45]
 [44 43 42 41 40]
 [39 38 37 36 35]
 [34 33 32 31 30]
 [29 28 27 26 25]
 [24 23 22 21 20]
 [19 18 17 16 15]
 [14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]


In [8]:
nz=np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4], dtype=int64),)

In [17]:
z=np.eye(3)
z
print((z))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [47]:
z=np.random.random((3,3,3))
z

array([[[0.0303448 , 0.86897343, 0.82500699],
        [0.88953296, 0.40838764, 0.10156232],
        [0.32152324, 0.90396991, 0.71788161]],

       [[0.49777435, 0.87621564, 0.88832056],
        [0.52586802, 0.96099985, 0.89314447],
        [0.75513902, 0.37143752, 0.36358929]],

       [[0.04064739, 0.1011882 , 0.61568589],
        [0.08247914, 0.62558246, 0.78351142],
        [0.45483616, 0.85680361, 0.82553325]]])

In [3]:
a=np.asarray([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [9]:
pip install Pandas

     ---------------------------------------- 10.3/10.3 MB 1.3 MB/s eta 0:00:00
     -------------------------------------- 499.4/499.4 kB 3.9 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [10]:
import pandas as pd

In [15]:
import pandas as pd
df=pd.DataFrame({'a1':[1,2,3],
                 'a2':[4,5,6]},
                index=['x','y','z'])
print('Dataframe: ')
print(df)

x=df.to_numpy()
print(x)

y=df.index.to_numpy()
print(y)


Dataframe: 
   a1  a2
x   1   4
y   2   5
z   3   6
[[1 4]
 [2 5]
 [3 6]]
['x' 'y' 'z']


In [22]:
x=np.array([[1,2],[3,4],[5,6]])

print(x)

y=x[:,0]
print("first",y)

s=x[:,1]
print("second",s)

a=x[1:,]
print("third",y)

[[1 2]
 [3 4]
 [5 6]]
first [1 3 5]
second [2 4 6]
third [1 3 5]


In [28]:
yesterday= np.datetime64('today','D') -np.timedelta64(1,'D')
toady= np.datetime64('today','D') 
tomorrow= np.datetime64('today','D') +np.timedelta64(1,'D')
print(yesterday)
print(toady)
print(tomorrow)

2023-01-24
2023-01-25
2023-01-26


In [30]:
z=np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [1]:
'''
numpy:
scalar vector array 

sci lib to work o the number => numpy 







'''


'\nnumpy:\nscalar vector array \n\nsci lib to work o the number => numpy \n\n\n\n\n\n\n\n'

In [2]:

'''

pip package manager for python 
    third party library() from internet 
    

'''

'\n\npip package manager for python \n    third party library() from internet \n    \n\n'

In [3]:
import numpy as np 

In [49]:
a=(np.array([ [1,2],[2,6] ]))

In [28]:
a.ndim

3

In [27]:
a=(np.array( [[[1, 2], [4, 5]], [[6, 7], [7, 8]]]))

In [29]:
a

array([[[1, 2],
        [4, 5]],

       [[6, 7],
        [7, 8]]])

In [34]:
print(np.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [61]:
a

array([[1, 2],
       [2, 6]])

In [60]:
a.max(axis=0)

array([2, 6])

In [62]:
b=np.array([[6,7,8],[9,10,11]])

In [73]:
c=np.array([[10,20,30],[40,50,60]])


In [80]:
b.T

array([[ 6,  9],
       [ 7, 10],
       [ 8, 11]])

In [88]:
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [106]:
import pandas as pd
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [131]:
ss=pd.Series([1,2,3,4]) # object=>  any non numrical data
ss

0    1
1    2
2    3
3    4
dtype: int64

In [114]:
dict1=pd.Series({"name":"sameer","name1":"saleem"}) 

In [115]:
dict1.index

Index(['name', 'name1'], dtype='object')

In [121]:
ss.index

RangeIndex(start=0, stop=5, step=1)

In [128]:
x=ss.to_numpy()

In [132]:
ss.max()


4

In [133]:
ss.idxmax()

3

In [154]:
# data frame 

# combination of several individual series 
pd.DataFrame({"Product":[10,20,30,40], "PName":('A','B','C','D')},index=[1,2,3,4])


Product PName
1       10     A
2       20     B
3       30     C
4       40     D

In [151]:
pid=pd.Series([10,20,30,40])
df=pd.DataFrame({"Product":pid,"PName":('A','B','C','D')})
df

Product PName
0       10     A
1       20     B
2       30     C
3       40     D

In [155]:
df.rename(columns={'Product': 'column1', 'PName': 'column2'}, inplace=True)

In [156]:
df


column1 column2
0       10       A
1       20       B
2       30       C
3       40       D

In [161]:
aa=pd.DataFrame([["Product1", 999],["Product 2", 1000]], index=['A','B'], columns=["ProdictName","ProductPrice"])

In [162]:
df_copy=aa.copy()

In [163]:
df_copy

ProdictName  ProductPrice
A    Product1           999
B   Product 2          1000